<?php

/**
* Implements hook_user_view().
*/
function doctor_tweak_user_view($account, $view_mode, $language){
   if($view_mode == 'full'){
    drupal_add_js(drupal_get_path('module', 'doctor_tweak') . '/js/responsive_tweak.js');
   }
}


/**
* hook_block_info().
*/
function doctor_tweak_block_info(){

  $blocks['flow_bar'] = array(
  	'info' => t('Flow bar'),
  	'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;

}
/**
* Implements hool_block_view().
*/
function doctor_tweak_block_view($delta){
  $block = array();
  switch($delta){
  	case 'flow_bar':
  	$block['subject'] = '';
  	$block['content'] = array(
       '#markup' => '<div>helll</div>',
       '#attached' => array(
       	  'css' => array(
       	  	 drupal_get_path('module', 'doctor_tweak') . '/css/flow_bar.css',
       	  	),
       	  'js' => array(
       	  	drupal_get_path('module', 'doctor_tweak') . '/js/weixin.js',
       	  	),
       	  ),
       	);

  	break;
  }

  return $block;
}
